---
- name: Configure a server to host Scaphandre runners
  gather_facts: true
  hosts: all
  become: true
  vars_files:
    - vars/main.yml
  tasks:
    - name: System details
      debug:
        msg: "{{ ansible_facts['lsb']['release'] }}"
    
    - name: Update all packages to their latest version
      apt:
        name: "*"
        state: latest
        update_cache: true
    
    - name: test rapl support
      shell: modprobe intel_rapl_common
      register: response
    - debug: msg="{{ response.stdout }}"
    
    - name: Install docker, curl
      apt:
        name: "docker.io"
        state: latest

    - name: Ensure docker daemon is running
      service:
        name: "docker"
        state: started
        enabled: true

    - name: Install and register Gitlab runner(s)
      include_role:
        name: riemers.gitlab-runner
